architecture: densenet201
n_epochs: 300
patience: 20
learning_rate: 0.0001
weight_decay: 0.01
batch_size: 32
input_size: [224, 224]
train_fpath: /Users/vribeiro/Documentos/workspace/isic_challenge_2020/data/fold_1/train.csv
valid_fpath: /Users/vribeiro/Documentos/workspace/isic_challenge_2020/data/fold_1/valid.csv
test_fpath: /Users/vribeiro/Documentos/workspace/isic_challenge_2020/data/test.csv