architecture: resnet101
n_epochs: 300
patience: 20
learning_rate: 0.0001
weight_decay: 0.01
batch_size: 32
input_size: [224, 224]
datapath: /datasets/isic_challenge_2020
train_fpath: /workspace/isic_challenge_2020/data/fold_1/train.csv
valid_fpath: /workspace/isic_challenge_2020/data/fold_1/valid.csv
test_fpath: /workspace/isic_challenge_2020/data/test.csv